### PR TITLE
Update crop.dart

### PR DESCRIPTION
**Pull request by RohitKumarMishra**
Added ImageStreamListner to imagestream listners which was causing errors in android.

### CODE REVIEW

**Comment by VolodymyrLykhonis** [comment]
Can you elaborate what's the error and why it's on Android only? This code is dart, it is same for iOS and Android. According to current analysis of Flutter pub, there is no error https://pub.dev/packages/image_crop#-analysis-tab-

**Comment by RohitKumarMishra** [comment]
it was showing listner was called on null. as imagestreamlsitner method was
not hving any type.

**Comment by RohitKumarMishra** [comment]
The argument type 'void Function(ImageInfo, bool)' can't
be assigned to the parameter type 'ImageStreamListener'.

**Comment by RohitKumarMishra** [comment]
I was using it on android and did not checked for ios, but it was working
after editing changes.
Regards,
Rohit Kumar Mishra
+91 8104599906
skype- rohitkumarmishra001

**Comment by VolodymyrLykhonis** [comment]
I guess I am having difficulty understanding the change that could address the error you were seeing. I do not see it in the code. Can you point it out in the comments of the code where the error was and why it was happening?

**Comment by RohitKumarMishra** [comment]
image_crop-0.2.1/lib/src/crop.dart:120:34: Error: The argument type 'void
Function(ImageInfo, bool)' can't
be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart'
('file:///flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from
'package:flutter/src/painting/image_stream.dart'
('file:///flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to
'ImageStreamListener'.
    _imageStream?.removeListener(_updateImage);




oldImageStream?.removeListener(_updateImage);
_imageStream.addListener(_updateImage);


these were having problem line number 158 and 159.

and below method causing problems -
void _updateImage(ImageInfo imageInfo, bool synchronousCall) {
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
setState(() {
_image = imageInfo.image;
_scale = imageInfo.scale;
_ratio = max(
_boundaries.width / _image.width,
_boundaries.height / _image.height,
);

final viewWidth = _boundaries.width / (_image.width * _scale * _ratio);
final viewHeight =
_boundaries.height / (_image.height * _scale * _ratio);
_area = _calculateDefaultArea(
viewWidth: viewWidth,
viewHeight: viewHeight,
imageWidth: _image.width,
imageHeight: _image.height,
);
_view = Rect.fromLTWH(
(1.0 - viewWidth) / 2 + _area.left,
(1.0 - viewHeight) / 2 + _area.top,
viewWidth,
viewHeight,
);
});
});
WidgetsBinding.instance.ensureVisualUpdate();
}




And for resolution you can see my changes in code.
Thanks

**Comment by RohitKumarMishra** [comment]
Also getting below issue specific to android -

 java.lang.RuntimeException: Methods marked with @UiThread must be executed
on the main thread. Current thread: pool-2-thread-1
E/AndroidRuntime( 1729):        at
io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime( 1729):        at
io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime( 1729):        at
io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime( 1729):        at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime( 1729):        at
com.lykhonis.imagecrop.ImageCropPlugin$1.run(ImageCropPlugin.java:144)
E/AndroidRuntime( 1729):        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 1729):        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 1729):        at java.lang.Thread.run(Thread.java:764)
I/Process ( 1729): Sending signal. PID: 1729 SIG: 9


This happens when we try to crop the selected image.

Thanks

**Comment by VolodymyrLykhonis** [comment]
Based on logs you are using version 0.2.1. Please try version 0.3.0 instead.

**Comment by RohitKumarMishra** [comment]
Just checked , it is working fine.
Thanks

**Pull request closed without merging**
