### PR TITLE
Add snap image flag

### PR DESCRIPTION
**Pull request by knezzz**
Setting 'snapImage' to false will no longer realign the image on end of drag to the middle.

Defaults to true to keep current behavior on older versions.

### CODE REVIEW

**Comment by VolodymyrLykhonis** [comment]
If image out of bounds, that would create empty space. When it's cropped and rendered into new image, it would contain black empty space. I am not sure it would good for users. Thoughts?

**Comment by knezzz** [comment]
Yeah, agreed. I wanted to add snapping when image goes out of bounds but still no luck. We currently need flexibility so this works for us, so if you don't mind leaving it open until I find solution to snap only when you leave image, i can update the PR then. :)

**Comment by VolodymyrLykhonis** [comment]
I am aware there are some weird areas of editing the image. I am sure need to spend time on improving it. Totally, if you can improve snapping or zoom to get image cropped better, it would be great.

In any case I keep this open and thank you for contribution and interest in the plugin.

**Comment by VolodymyrLykhonis** [comment]
Closing this one for now. Please see v0.1.2.

**Pull request closed without merging**
