### PR TITLE
 Fixed image rotation bug after cropping

### PR DESCRIPTION
**Pull request by igorstr**
Changed method **CGImageSourceCreateImageAtIndex** to **CGImageSourceCreateThumbnailAtIndex**, with **CFDictionaryRef** contains key **kCGImageSourceCreateThumbnailWithTransform : @YES**. 

Without transform key image gets rotated by 90 degree

### CODE REVIEW

**Comment by VolodymyrLykhonis** [comment]
@igorstr this is great! Thank you for your contribution. Can you please squash your commits into a single one with description (like the first commit) and I will merge it ASAP.

**Comment by igorstr** [comment]
> @igorstr this is great! Thank you for your contribution. Can you please squash your commits into a single one with description (like the first commit) and I will merge it ASAP.

Done.

**Comment by japborst** [comment]
Hey @VolodymyrLykhonis, I see this is merged but will this be released? Would be nice to update and remove the bug :)

**Comment by igorstr** [comment]
Agree with @japborst. New version is required. Yes, this is a small fix , but this bug is critical for iOS. 
Right now I am forced to include plugin as local one.

**Comment by VolodymyrLykhonis** [comment]
Working through this to push as 0.3.2 now. @japborst @igorstr

**Pull request merged**
